FROM python:3.10.2-alpine3.15
COPY . .
# Install Postgres
RUN mkdir -p /root/workspace/src
RUN mkdir -p /run/postgresql/
WORKDIR /run/postgresql/
RUN apk update
RUN apk add postgresql 
RUN chown postgres:postgres /run/postgresql/
# Install requirements
COPY ./requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt
# For psycopg2
RUN apk add --virtual postgresql-deps libpq-dev
# Create directories

# Mount your local file
COPY ./main.py /root/workspace/src
# Switch to project directory
WORKDIR /root/workspace/src

